#include "application.hpp"
#include "agent_loop.hpp"
#include "command_tool.hpp"
#include "contract.hpp"
#include "error.hpp"
#include "line_editor.hpp"
#include "llama_runtime.hpp"
#include "lua_agent.hpp"
#include "terminal.hpp"
#include "tools.hpp"
#include "workspace.hpp"
#include <csignal>
#include <fstream>
#include <iostream>
#include <sstream>
#include <thread>
#include <sys/stat.h>
#include <unistd.h>
#ifndef G9_LLAMA_CPP_REVISION
#define G9_LLAMA_CPP_REVISION "f3f1a8f2760f28325a5ec20c05b171e5b7c83a29"
#endif
namespace g9 {namespace {
Access parse_access(std::string_view s){if(s=="rw")return Access::read_write;if(s=="r")return Access::read;if(s=="none")return Access::none;throw Error(ExitCode::lua_failure,"invalid Lua workspace access: "+std::string(s));}GuardrailProfile parse_profile(std::string_view s){if(s=="review")return GuardrailProfile::review;if(s=="balanced")return GuardrailProfile::balanced;if(s=="autonomous")return GuardrailProfile::autonomous_mode;throw Error(ExitCode::lua_failure,"invalid Lua guardrail profile: "+std::string(s));}SandboxMode parse_sandbox(std::string_view s){if(s=="strict")return SandboxMode::strict;if(s=="best-effort")return SandboxMode::best_effort;if(s=="off")return SandboxMode::off;throw Error(ExitCode::lua_failure,"invalid Lua command sandbox: "+std::string(s));}
std::filesystem::path canonical_dir(const std::filesystem::path&p,const char*what){std::error_code ec;auto c=std::filesystem::canonical(p,ec);if(ec||!std::filesystem::is_directory(c))throw Error(ExitCode::invalid_input,std::string(what)+" is not an existing directory: "+p.string());return c;}std::filesystem::path resolve_agent_root(const CliOptions&o){if(o.agent_root)return canonical_dir(*o.agent_root,"agent root");std::vector<std::filesystem::path>candidates{std::filesystem::current_path()};if(!o.program_path.empty()){std::error_code ec;auto p=std::filesystem::weakly_canonical(o.program_path,ec);if(!ec){p=p.parent_path();for(int i=0;i<4&&!p.empty();++i){candidates.push_back(p);p=p.parent_path();}}}for(auto&p:candidates)if(std::filesystem::exists(p/"config/agent.lua"))return canonical_dir(p,"agent root");throw Error(ExitCode::invalid_input,"cannot locate agent root; use ./run.sh or --agent-root PATH");}std::filesystem::path resolve_relative(const std::filesystem::path&base,const std::filesystem::path&p){return p.is_absolute()?p:base/p;}
void append_audit(const std::optional<std::filesystem::path>&path,const JsonValue&v){if(!path)return;std::error_code ec;if(!path->parent_path().empty())std::filesystem::create_directories(path->parent_path(),ec);std::ofstream f(*path,std::ios::app);if(f){f<<serialize_json(v)<<'\n';f.close();::chmod(path->c_str(),0600);}}
volatile sig_atomic_t signal_write_fd=-1;void on_sigint(int){int fd=(int)signal_write_fd;if(fd>=0){char c=1;(void)::write(fd,&c,1);}}
class TaskSignal{public:TaskSignal(){if(pipe(fds_)!=0)throw Error(ExitCode::internal_failure,"cannot create signal pipe");signal_write_fd=fds_[1];struct sigaction sa{};sa.sa_handler=on_sigint;sigemptyset(&sa.sa_mask);sigaction(SIGINT,&sa,&old_);watcher_=std::jthread([this](std::stop_token){char c;if(::read(fds_[0],&c,1)>0&&c!=0)source_.request_stop();});}~TaskSignal(){sigaction(SIGINT,&old_,nullptr);signal_write_fd=-1;char c=0;(void)::write(fds_[1],&c,1);if(watcher_.joinable())watcher_.join();::close(fds_[1]);::close(fds_[0]);}std::stop_token token()const{return source_.get_token();}private:int fds_[2]{-1,-1};struct sigaction old_{};std::stop_source source_;std::jthread watcher_;};
std::string slash_help(){return "/help  /status  /scope  /policy  /tools  /changes  /thinking [on|off]  /clear  /exit";}
}
struct Application::BaseState{std::filesystem::path root,config_path,model_path,temp_root;LuaAgent policy;Access default_access;std::vector<ScopeRule>scopes;std::vector<std::string>denies;GuardrailProfile profile;SandboxMode sandbox_mode;Workspace workspace;Guardrails guardrails;ProcessSandbox sandbox;ToolRegistry tools;CodingTools file_tools;CommandTool command_tool;BaseState(std::filesystem::path ar,std::filesystem::path cp,std::filesystem::path mp,std::filesystem::path temp,LuaAgent&&pol,Access da,std::vector<ScopeRule>sc,std::vector<std::string>de,GuardrailProfile gp,SandboxMode sm,std::filesystem::path wr):root(std::move(ar)),config_path(std::move(cp)),model_path(std::move(mp)),temp_root(std::move(temp)),policy(std::move(pol)),default_access(da),scopes(std::move(sc)),denies(std::move(de)),profile(gp),sandbox_mode(sm),workspace(std::move(wr),default_access,scopes,denies,policy.workspace_policy().follow_directory_symlinks),guardrails(profile),sandbox(ProcessSandbox::detect(sandbox_mode,workspace,root,temp_root)),tools(guardrails),file_tools(workspace),command_tool(workspace,sandbox,root,temp_root){register_file_tools(tools,file_tools);register_command_tool(tools,command_tool);}~BaseState(){std::error_code ec;std::filesystem::remove_all(temp_root,ec);}};
std::unique_ptr<Application::BaseState>Application::build_base(){auto root=resolve_agent_root(options_);auto config=options_.config?resolve_relative(std::filesystem::current_path(),*options_.config):root/"config/agent.lua";if(!std::filesystem::exists(config))throw Error(ExitCode::lua_failure,"config not found: "+config.string());LuaAgent policy(config,[](std::string_view s){std::cerr<<s;});if(options_.thinking)policy.set_thinking(*options_.thinking);if(options_.max_steps){if(*options_.max_steps>256)throw Error(ExitCode::invalid_input,"max steps cannot exceed 256");policy.set_max_steps(*options_.max_steps);}auto pc=policy.workspace_policy();Access da=parse_access(pc.default_access);std::vector<ScopeRule>sc;for(auto&s:pc.scopes)sc.push_back({s.path,parse_access(s.access)});sc.insert(sc.end(),options_.scopes.begin(),options_.scopes.end());auto denies=pc.deny;denies.insert(denies.end(),options_.denies.begin(),options_.denies.end());auto gp=options_.profile.value_or(parse_profile(policy.guardrail_policy().profile));auto sm=options_.command_sandbox.value_or(parse_sandbox(policy.guardrail_policy().command_sandbox));auto workspace=canonical_dir(options_.workspace,"workspace");auto model=options_.model?resolve_relative(std::filesystem::current_path(),*options_.model):resolve_relative(root,policy.model().path);auto temp=std::filesystem::temp_directory_path()/("g9-agent-"+std::to_string(::getpid()));return std::make_unique<BaseState>(root,config,model,temp,std::move(policy),da,std::move(sc),std::move(denies),gp,sm,workspace);}
int Application::run(){switch(options_.mode){case InvocationMode::chat:return run_chat();case InvocationMode::json_run:return run_json_contract();case InvocationMode::doctor:return run_doctor();case InvocationMode::tools:return run_tools();case InvocationMode::version:return run_version();case InvocationMode::help:return run_help();}return 10;}int Application::run_version(){std::cout<<"g9-agent 0.1.0\nllama.cpp "<<G9_LLAMA_CPP_REVISION<<"\nLua baseline 5.4.9\n";return 0;}int Application::run_help(){std::cout<<usage_text();return 0;}
int Application::run_doctor(){auto b=build_base();bool ok=true;std::error_code ec;auto size=std::filesystem::file_size(b->model_path,ec);if(ec)ok=false;std::cout<<"G9 doctor\nagent_root: "<<b->root<<"\nconfig: "<<b->config_path<<" (ok)\nmodel: "<<b->model_path<<" ("<<(ec?"missing":"present")<<")\n";if(!ec)std::cout<<"model_bytes: "<<size<<"\n";std::cout<<"workspace: "<<b->workspace.root()<<"\nprofile: "<<to_string(b->profile)<<"\nsandbox: "<<b->sandbox.capabilities().backend<<"\nsandbox_detail: "<<b->sandbox.capabilities().detail<<"\nsandbox_filesystem: "<<(b->sandbox.capabilities().filesystem?"yes":"no")<<"\nsandbox_network: "<<(b->sandbox.capabilities().network?"yes":"no")<<"\nstrict_ready: "<<(b->sandbox.strict_ready()?"yes":"no")<<"\nllama.cpp: "<<G9_LLAMA_CPP_REVISION<<"\nLua: 5.4.9 baseline\ntools:";for(auto&t:b->tools.definitions())std::cout<<' '<<t.name;std::cout<<"\n";if(b->sandbox_mode==SandboxMode::strict&&!b->sandbox.strict_ready())ok=false;return ok?0:1;}
int Application::run_tools(){auto b=build_base();for(auto&t:b->tools.definitions())std::cout<<t.name<<" ["<<to_string(t.base_risk)<<"] - "<<t.description<<"\n";return 0;}
int Application::run_json_contract(){auto b=build_base();std::string raw;raw.reserve(65536);char buf[8192];while(std::cin){std::cin.read(buf,sizeof buf);auto n=std::cin.gcount();if(n>0){if(raw.size()+(size_t)n>1024*1024)throw Error(ExitCode::invalid_input,"JSON request exceeds 1 MiB");raw.append(buf,(size_t)n);}}auto request=parse_request(parse_json(raw));if(!std::filesystem::exists(b->model_path))throw Error(ExitCode::model_failure,"model file not found: "+b->model_path.string());LlamaRuntime runtime(b->model_path,b->policy.model(),[](std::string_view s){std::cerr<<s;});Session session;auto events=[&](const LoopEvent&e){append_audit(options_.audit_log,JsonValue::object{{"event",(double)(int)e.type},{"summary",e.summary},{"detail",e.detail}});};AgentLoop loop(b->policy,runtime,b->tools,b->guardrails,[](const ActionDescriptor&){return PolicyAction::deny;},events);TaskSignal sig;auto r=loop.run(session,request,sig.token());AgentResponse response{r.output,"ai9stars/G9v3-3B",r.usage,JsonValue::object{{"tool_steps",(double)r.tool_steps},{"workspace_status",b->file_tools.status()}}};std::cout<<serialize_json(response_to_json(response))<<'\n';return 0;}
int Application::run_chat(){auto b=build_base();if(!std::filesystem::exists(b->model_path))throw Error(ExitCode::model_failure,"model file not found: "+b->model_path.string());Terminal term(options_.color);term.banner("ai9stars/G9v3-3B",b->workspace.root(),b->profile,b->sandbox.capabilities());LlamaRuntime runtime(b->model_path,b->policy.model(),[](std::string_view s){std::cerr<<s;});Session session;LineEditor editor;editor.set_completions({"/help","/status","/scope","/policy","/tools","/changes","/thinking on","/thinking off","/clear","/exit"});editor.set_history_file(options_.history_file);auto events=[&](const LoopEvent&e){term.event(e);append_audit(options_.audit_log,JsonValue::object{{"event",(double)(int)e.type},{"summary",e.summary},{"detail",e.detail}});};auto approval=[&](const ActionDescriptor&a){append_audit(options_.audit_log,JsonValue::object{{"approval_requested",a.summary},{"risk",to_string(a.risk)}});auto c=term.approval(a);if(c==ApprovalChoice::session&&!a.equivalence_key.empty()){b->guardrails.allow_for_session(a.equivalence_key);return PolicyAction::allow;}return c==ApprovalChoice::once?PolicyAction::allow:PolicyAction::deny;};AgentLoop loop(b->policy,runtime,b->tools,b->guardrails,approval,events);for(;;){auto line=editor.read("g9> ");if(line.status==ReadStatus::eof)break;if(line.status==ReadStatus::interrupted)continue;if(line.text.empty())continue;editor.add_history(line.text);if(line.text[0]=='/'){std::istringstream in(line.text);std::string cmd,arg;in>>cmd>>arg;if(cmd=="/exit")break;if(cmd=="/help"){term.info(slash_help());continue;}if(cmd=="/clear"){session.clear();term.info("session cleared");continue;}if(cmd=="/thinking"){if(arg=="on")b->policy.set_thinking(true);else if(arg=="off")b->policy.set_thinking(false);else{term.warning("usage: /thinking on|off");continue;}term.info(std::string("thinking: ")+(b->policy.generation().thinking?"on":"off"));continue;}if(cmd=="/changes"){term.info(serialize_json(b->file_tools.status()));continue;}if(cmd=="/tools"){for(auto&t:b->tools.definitions())term.info(t.name+" - "+t.description);continue;}if(cmd=="/policy"){term.info("profile: "+to_string(b->profile)+", sandbox: "+b->sandbox.capabilities().backend);continue;}if(cmd=="/scope"){term.info("workspace: "+b->workspace.root().string());for(auto&s:b->scopes)term.info("  "+s.relative_path.generic_string());for(auto&d:b->denies)term.info("  deny "+d);continue;}if(cmd=="/status"){term.info("model: "+b->model_path.string()+"\nworkspace: "+b->workspace.root().string()+"\nmessages: "+std::to_string(session.items().size()));continue;}term.warning("unknown slash command");continue;}try{TaskSignal sig;auto r=loop.run(session,AgentRequest{line.text},sig.token());term.answer(r.output);}catch(const Error&e){if(std::string_view(e.what()).find("cancel")!=std::string_view::npos)term.warning("task cancelled");else term.warning(e.what());}}return 0;}
}
