#include "cli.hpp"
#include "error.hpp"
#include <charconv>
namespace g9 {namespace {
std::string value(int&i,int argc,char**argv,const std::string&opt){if(i+1>=argc)throw Error(ExitCode::invalid_input,"missing value for "+opt);return argv[++i];}
Access access(std::string_view s){if(s=="r")return Access::read;if(s=="rw")return Access::read_write;if(s=="none")return Access::none;throw Error(ExitCode::invalid_input,"scope access must be r, rw, or none");}
GuardrailProfile profile(std::string_view s){if(s=="review")return GuardrailProfile::review;if(s=="balanced")return GuardrailProfile::balanced;if(s=="autonomous")return GuardrailProfile::autonomous_mode;throw Error(ExitCode::invalid_input,"invalid profile");}
SandboxMode sandbox(std::string_view s){if(s=="strict")return SandboxMode::strict;if(s=="best-effort")return SandboxMode::best_effort;if(s=="off")return SandboxMode::off;throw Error(ExitCode::invalid_input,"invalid command sandbox mode");}
uint32_t u32(std::string_view s,const char*what){uint32_t v{};auto[p,e]=std::from_chars(s.data(),s.data()+s.size(),v);if(e!=std::errc{}||p!=s.data()+s.size()||v==0)throw Error(ExitCode::invalid_input,std::string("invalid ")+what);return v;}
}
CliOptions parse_cli(int argc,char**argv){CliOptions o;if(argc>0)o.program_path=argv[0];bool json=false;int i=1;if(i<argc&&argv[i][0]!='-'){std::string cmd=argv[i++];if(cmd=="chat")o.mode=InvocationMode::chat;else if(cmd=="run")o.mode=InvocationMode::json_run;else if(cmd=="doctor")o.mode=InvocationMode::doctor;else if(cmd=="tools")o.mode=InvocationMode::tools;else if(cmd=="version")o.mode=InvocationMode::version;else if(cmd=="help")o.mode=InvocationMode::help;else throw Error(ExitCode::invalid_input,"unknown command: "+cmd);}for(;i<argc;++i){std::string a=argv[i];if(a=="--help"||a=="-h"){o.mode=InvocationMode::help;continue;}if(a=="--json"){json=true;continue;}if(a=="--workspace"){o.workspace=value(i,argc,argv,a);continue;}if(a=="--agent-root"){o.agent_root=value(i,argc,argv,a);continue;}if(a=="--config"){o.config=value(i,argc,argv,a);continue;}if(a=="--model"){o.model=value(i,argc,argv,a);continue;}if(a=="--history-file"){o.history_file=value(i,argc,argv,a);continue;}if(a=="--audit-log"){o.audit_log=value(i,argc,argv,a);continue;}if(a=="--profile"){o.profile=profile(value(i,argc,argv,a));continue;}if(a=="--deny"){o.denies.push_back(value(i,argc,argv,a));continue;}if(a=="--scope"){auto v=value(i,argc,argv,a);auto p=v.rfind(':');if(p==std::string::npos||p==0)throw Error(ExitCode::invalid_input,"scope syntax is PATH:r|rw|none");o.scopes.push_back({v.substr(0,p),access(v.substr(p+1))});continue;}if(a=="--max-steps"){o.max_steps=u32(value(i,argc,argv,a),"max steps");continue;}if(a=="--thinking"){auto v=value(i,argc,argv,a);if(v=="on")o.thinking=true;else if(v=="off")o.thinking=false;else throw Error(ExitCode::invalid_input,"--thinking requires on or off");continue;}if(a=="--color"){auto v=value(i,argc,argv,a);if(v=="auto")o.color=ColorMode::automatic;else if(v=="always")o.color=ColorMode::always;else if(v=="never")o.color=ColorMode::never;else throw Error(ExitCode::invalid_input,"--color requires auto, always, or never");continue;}if(a=="--command-sandbox"){o.command_sandbox=sandbox(value(i,argc,argv,a));continue;}if(a=="--verbose"){o.verbose=true;continue;}throw Error(ExitCode::invalid_input,"unknown option: "+a);}if(o.mode==InvocationMode::json_run&&!json)throw Error(ExitCode::invalid_input,"run requires --json");if(json&&o.mode!=InvocationMode::json_run)throw Error(ExitCode::invalid_input,"--json is only valid with run");return o;}
std::string usage_text(){return "g9-agent [chat] [options]\n  g9-agent run --json [options]\n  g9-agent doctor [options]\n  g9-agent tools [options]\n  g9-agent version\n\nOptions:\n  --workspace PATH\n  --config PATH\n  --model PATH\n  --profile review|balanced|autonomous\n  --scope PATH:r|rw|none   (repeatable)\n  --deny GLOB              (repeatable)\n  --command-sandbox strict|best-effort|off\n  --verbose                (show metadata and runtime logs)\n  --max-steps N\n  --thinking on|off\n  --history-file PATH      (history is disabled unless set)\n  --audit-log PATH\n  --color auto|always|never\n";}
}
