#include "command_tool.hpp"
#include "error.hpp"
#include <algorithm>
#include <sstream>
namespace g9 {namespace {
std::vector<std::string> argv_arg(const JsonValue&a){auto*v=object_get(a.as_object(),"command");if(!v||!v->is_array()||v->as_array().empty())throw Error(ExitCode::invalid_input,"run_command.command must be a non-empty array");std::vector<std::string>out;for(auto&x:v->as_array()){if(!x.is_string()||x.as_string().empty())throw Error(ExitCode::invalid_input,"run_command argv entries must be non-empty strings");out.push_back(x.as_string());}return out;}
std::string str_arg(const JsonValue&a,std::string_view k,std::string d){if(auto*v=object_get(a.as_object(),k)){if(!v->is_string())throw Error(ExitCode::invalid_input,"argument must be string: "+std::string(k));return v->as_string();}return d;}
size_t num_arg(const JsonValue&a,std::string_view k,size_t d,size_t max){if(auto*v=object_get(a.as_object(),k)){if(!v->is_number()||v->as_number()<0)throw Error(ExitCode::invalid_input,"argument must be number: "+std::string(k));return(std::min)((size_t)v->as_number(),max);}return d;}
bool system_path(const std::filesystem::path&p){auto s=p.lexically_normal().generic_string();return s=="/usr"||s.starts_with("/usr/")||s=="/bin"||s.starts_with("/bin/")||s=="/lib"||s.starts_with("/lib/")||s=="/lib64"||s.starts_with("/lib64/");}
void validate_explicit_paths(const Workspace&ws,const std::filesystem::path&cwd,const std::vector<std::string>&argv){std::error_code ec;auto cwd_rel=std::filesystem::relative(cwd,ws.root(),ec);if(ec)throw Error(ExitCode::policy_denied,"command cwd cannot be related to workspace");if(!argv.empty()&&argv[0].find('/')!=std::string::npos){std::filesystem::path p(argv[0]);if(p.is_absolute()){if(!system_path(p)){auto can=std::filesystem::weakly_canonical(p,ec);if(ec)throw Error(ExitCode::policy_denied,"cannot resolve explicit executable path: "+argv[0]);auto rel=std::filesystem::relative(can,ws.root(),ec);if(ec||rel.is_absolute()||(!rel.empty()&&*rel.begin()==".."))throw Error(ExitCode::policy_denied,"explicit executable path outside workspace: "+argv[0]);auto d=ws.resolve(rel,Operation::read);if(!d.allowed)throw Error(ExitCode::policy_denied,d.reason);}}else{auto rel=(cwd_rel/p).lexically_normal();auto d=ws.resolve(rel,Operation::read);if(!d.allowed)throw Error(ExitCode::policy_denied,d.reason);}}for(size_t i=1;i<argv.size();++i){std::string a=argv[i];bool write=false;std::string raw;if(a=="-o"&&i+1<argv.size()){raw=argv[++i];write=true;}else if((a.starts_with("-I")||a.starts_with("-L"))&&a.size()>2)raw=a.substr(2);else if(a.starts_with("--output=")){raw=a.substr(9);write=true;}else if(!a.empty()&&a[0]!='-'&&(a.find('/')!=std::string::npos||a[0]=='.'||std::filesystem::exists(cwd/a)))raw=a;if(raw.empty())continue;std::filesystem::path p(raw);if(p.is_absolute()){if(system_path(p)&&!write)continue;auto can=std::filesystem::weakly_canonical(p,ec);if(ec)throw Error(ExitCode::policy_denied,"cannot resolve explicit command path: "+raw);auto rel=std::filesystem::relative(can,ws.root(),ec);if(ec||rel.is_absolute()||(!rel.empty()&&*rel.begin()==".."))throw Error(ExitCode::policy_denied,"explicit command path outside workspace: "+raw);auto d=ws.resolve(rel,write?Operation::write:Operation::read,write);if(!d.allowed)throw Error(ExitCode::policy_denied,d.reason);}else{auto rel=(cwd_rel/p).lexically_normal();auto d=ws.resolve(rel,write?Operation::write:Operation::read,write);if(!d.allowed)throw Error(ExitCode::policy_denied,d.reason);}}}
std::string key_for(const std::vector<std::string>&a,const std::filesystem::path&cwd){std::string k="cmd:"+cwd.generic_string();for(auto&s:a){k.push_back('\0');k+=s;}return k;}
JsonValue schema(){return JsonValue::object{{"type","object"},{"properties",JsonValue::object{{"command",JsonValue::object{{"type","array"}}},{"cwd",JsonValue::object{{"type","string"}}},{"timeout_ms",JsonValue::object{{"type","integer"}}},{"max_output_bytes",JsonValue::object{{"type","integer"}}}}},{"required",JsonValue::array{JsonValue("command")}},{"additionalProperties",false}};}
}
ActionDescriptor CommandTool::preflight(const JsonValue&a)const{auto argv=argv_arg(a);auto cwd_rel=str_arg(a,"cwd",".");auto cwd=workspace_.resolve(cwd_rel,Operation::execute_cwd);if(!cwd.allowed)throw Error(ExitCode::policy_denied,cwd.reason);validate_explicit_paths(workspace_,cwd.canonical_path,argv);ActionDescriptor d;d.tool="run_command";d.command_argv=argv;d.targets={cwd.canonical_path};d.risk=policy_.risk(argv);if(sandbox_.mode()==SandboxMode::strict&&!sandbox_.strict_ready())d.risk=RiskClass::forbidden;else if(sandbox_.mode()==SandboxMode::off||(sandbox_.mode()==SandboxMode::best_effort&&(!sandbox_.capabilities().filesystem||!sandbox_.capabilities().network)))d.risk=RiskClass::unsandboxed_execute;d.equivalence_key=key_for(argv,cwd.canonical_path);std::ostringstream s;s<<"run";for(auto&x:argv)s<<' '<<x;d.summary=s.str();return d;}
ToolResult CommandTool::execute(const JsonValue&a)const{auto argv=argv_arg(a);auto cwd=workspace_.resolve(str_arg(a,"cwd","."),Operation::execute_cwd);if(!cwd.allowed)throw Error(ExitCode::policy_denied,cwd.reason);validate_explicit_paths(workspace_,cwd.canonical_path,argv);if(sandbox_.mode()==SandboxMode::strict&&!sandbox_.strict_ready())throw Error(ExitCode::policy_denied,"strict process sandbox unavailable");std::filesystem::create_directories(temp_root_);ProcessSpec spec;spec.argv=std::move(argv);spec.cwd=cwd.canonical_path;spec.timeout=std::chrono::milliseconds(num_arg(a,"timeout_ms",120000,3600000));spec.max_output_bytes=num_arg(a,"max_output_bytes",131072,1048576);spec.environment=minimal_environment(temp_root_/"home",temp_root_);std::filesystem::create_directories(temp_root_/"home");auto r=run_process(spec,[this]{if(sandbox_.mode()!=SandboxMode::off&&sandbox_.capabilities().filesystem)sandbox_.apply_in_child();});JsonValue payload=JsonValue::object{{"exit_code",r.exit_code},{"timed_out",r.timed_out},{"cancelled",r.cancelled},{"stdout",r.stdout_text},{"stderr",r.stderr_text},{"stdout_truncated",r.stdout_truncated},{"stderr_truncated",r.stderr_truncated},{"duration_ms",(double)r.duration.count()}};ToolResult out;out.disposition=ToolDisposition::completed;out.ok=r.exit_code==0&&!r.timed_out&&!r.cancelled;out.payload=std::move(payload);out.display_summary="command exited "+std::to_string(r.exit_code);return out;}
void register_command_tool(ToolRegistry&r,CommandTool&t){r.add({"run_command","Run an approved local command by argv without a shell",schema(),RiskClass::execute},[&t](const JsonValue&a){return t.preflight(a);},[&t](const JsonValue&a){return t.execute(a);});}
}
