#include "line_editor.hpp"
#include <cerrno>
#include <fstream>
#include <iostream>
#include <string_view>
#include <sys/stat.h>
#include <termios.h>
#include <unistd.h>
namespace g9 { namespace {
size_t prev_cp(std::string_view s,size_t p){if(!p)return 0;--p;while(p&&((unsigned char)s[p]&0xC0)==0x80)--p;return p;}size_t next_cp(std::string_view s,size_t p){if(p>=s.size())return s.size();++p;while(p<s.size()&&((unsigned char)s[p]&0xC0)==0x80)++p;return p;}void out(std::string_view s){(void)::write(STDOUT_FILENO,s.data(),s.size());}
struct Raw{termios old{};bool ok=false;Raw(){if(tcgetattr(STDIN_FILENO,&old)!=0)return;auto r=old;r.c_lflag&=~(ECHO|ICANON|IEXTEN|ISIG);r.c_iflag&=~(IXON|ICRNL|BRKINT|INPCK|ISTRIP);r.c_cflag|=CS8;r.c_oflag&=~OPOST;r.c_cc[VMIN]=1;r.c_cc[VTIME]=0;if(tcsetattr(STDIN_FILENO,TCSAFLUSH,&r)==0){ok=true;out("\x1b[?2004h");}}~Raw(){if(ok){out("\x1b[?2004l");tcsetattr(STDIN_FILENO,TCSAFLUSH,&old);}}};
void refresh(std::string_view prompt,const std::string&buf,size_t cursor){std::string s="\r\x1b[2K";s+=prompt;s+=buf;s+="\r";s+=prompt;if(cursor)s+="\x1b["+std::to_string(cursor)+"C";out(s);}bool read_byte(char&c){for(;;){ssize_t n=::read(STDIN_FILENO,&c,1);if(n==1)return true;if(n==0)return false;if(errno!=EINTR)return false;}}
std::string read_paste(){std::string b;const std::string end="\x1b[201~";std::string pending;char c;while(read_byte(c)){pending.push_back(c);while(!pending.empty()&&end.substr(0,pending.size())!=pending){b.push_back(pending.front());pending.erase(pending.begin());}if(pending==end)break;if(b.size()>1024*1024)break;}std::string n;for(size_t i=0;i<b.size();++i){if(b[i]=='\r'){n+='\n';if(i+1<b.size()&&b[i+1]=='\n')++i;}else n+=b[i];}return n;}
}
void LineEditor::set_history_file(std::optional<std::filesystem::path>p){history_file_=std::move(p);history_.clear();load_history();}void LineEditor::load_history(){if(!history_file_)return;std::ifstream f(*history_file_);std::string l;while(std::getline(f,l)){if(!l.empty())history_.push_back(l);if(history_.size()>history_limit_)history_.erase(history_.begin());}}void LineEditor::save_history()const{if(!history_file_)return;std::error_code ec;auto parent=history_file_->parent_path();if(!parent.empty())std::filesystem::create_directories(parent,ec);std::ofstream f(*history_file_,std::ios::trunc);for(auto&l:history_)f<<l<<'\n';f.close();::chmod(history_file_->c_str(),0600);}void LineEditor::add_history(std::string_view line){if(line.empty())return;if(history_.empty()||history_.back()!=line)history_.emplace_back(line);if(history_.size()>history_limit_)history_.erase(history_.begin(),history_.begin()+(history_.size()-history_limit_));save_history();}
ReadLineResult LineEditor::read(std::string_view prompt){if(!isatty(STDIN_FILENO)||!isatty(STDOUT_FILENO)){std::string l;if(!std::getline(std::cin,l))return{ReadStatus::eof,{}};return{ReadStatus::line,std::move(l)};}Raw raw;if(!raw.ok){std::string l;std::cout<<prompt<<std::flush;if(!std::getline(std::cin,l))return{ReadStatus::eof,{}};return{ReadStatus::line,std::move(l)};}std::string b;size_t cur=0,hidx=history_.size();refresh(prompt,b,cur);for(;;){char c;if(!read_byte(c)){out("\r\n");return{ReadStatus::eof,{}};}unsigned char u=(unsigned char)c;if(u==13||u==10){out("\r\n");return{ReadStatus::line,b};}if(u==3){out("^C\r\n");return{ReadStatus::interrupted,{}};}if(u==4&&b.empty()){out("\r\n");return{ReadStatus::eof,{}};}if(u==127||u==8){if(cur){auto p=prev_cp(b,cur);b.erase(p,cur-p);cur=p;refresh(prompt,b,cur);}continue;}if(u==1){cur=0;refresh(prompt,b,cur);continue;}if(u==5){cur=b.size();refresh(prompt,b,cur);continue;}if(u==21){b.clear();cur=0;refresh(prompt,b,cur);continue;}if(u==9){std::vector<std::string>m;for(auto&x:completions_)if(x.starts_with(b))m.push_back(x);if(m.size()==1){b=m[0];cur=b.size();refresh(prompt,b,cur);}else if(m.size()>1){out("\r\n");for(auto&x:m){out(x);out("  ");}out("\r\n");refresh(prompt,b,cur);}continue;}if(u==27){char a,d;if(!read_byte(a))continue;if(a=='['){if(!read_byte(d))continue;if(d=='A'){if(!history_.empty()&&hidx>0){--hidx;b=history_[hidx];cur=b.size();refresh(prompt,b,cur);}}else if(d=='B'){if(hidx<history_.size()){++hidx;b=hidx<history_.size()?history_[hidx]:"";cur=b.size();refresh(prompt,b,cur);}}else if(d=='C'){cur=next_cp(b,cur);refresh(prompt,b,cur);}else if(d=='D'){cur=prev_cp(b,cur);refresh(prompt,b,cur);}else if(d=='H'){cur=0;refresh(prompt,b,cur);}else if(d=='F'){cur=b.size();refresh(prompt,b,cur);}else if(d=='2'){char seq[3];if(read_byte(seq[0])&&read_byte(seq[1])&&read_byte(seq[2])&&seq[0]=='0'&&seq[1]=='0'&&seq[2]=='~'){auto p=read_paste();b.insert(cur,p);cur+=p.size();refresh(prompt,b,cur);}}}continue;}b.insert(cur,1,c);++cur;refresh(prompt,b,cur);}}
}
