#include "llama_runtime.hpp"
#include "error.hpp"
#include <llama.h>
#include <algorithm>
#include <array>
#include <climits>
#include <thread>
#include <utility>
#include <vector>
namespace g9 {namespace {
struct BackendLifetime{BackendLifetime(){llama_backend_init();}~BackendLifetime(){llama_backend_free();}};BackendLifetime&backend(){static BackendLifetime b;return b;}int threads_for(int r){if(r>0)return r;auto n=std::thread::hardware_concurrency();return(std::max)(1u,n?n:1u);}std::vector<llama_token>tokenize(const llama_vocab*vocab,std::string_view text){int32_t n=llama_tokenize(vocab,text.data(),(int32_t)text.size(),nullptr,0,false,true);if(n==INT32_MIN)throw Error(ExitCode::context_failure,"tokenization overflow");if(n>=0)return{};n=-n;std::vector<llama_token>out((size_t)n);auto got=llama_tokenize(vocab,text.data(),(int32_t)text.size(),out.data(),n,false,true);if(got<0)throw Error(ExitCode::inference_failure,"tokenization failed");out.resize((size_t)got);return out;}std::string piece(const llama_vocab*vocab,llama_token token){std::array<char,256>small{};int32_t n=llama_token_to_piece(vocab,token,small.data(),(int32_t)small.size(),0,false);if(n>=0)return std::string(small.data(),(size_t)n);std::vector<char>big((size_t)-n);n=llama_token_to_piece(vocab,token,big.data(),(int32_t)big.size(),0,false);if(n<0)throw Error(ExitCode::inference_failure,"token to piece failed");return std::string(big.data(),(size_t)n);}
}
struct LlamaRuntime::Impl{ModelConfig cfg;std::function<void(std::string_view)>sink;llama_model*model=nullptr;const llama_vocab*vocab=nullptr;explicit Impl(std::filesystem::path p,const ModelConfig&c,std::function<void(std::string_view)>s):cfg(c),sink(std::move(s)){(void)backend();llama_log_set([](ggml_log_level,const char*text,void*ud){auto*f=static_cast<std::function<void(std::string_view)>*>(ud);if(f&&*f&&text)(*f)(text);},&sink);auto mp=llama_model_default_params();mp.n_gpu_layers=cfg.gpu_layers;model=llama_model_load_from_file(p.string().c_str(),mp);if(!model)throw Error(ExitCode::model_failure,"failed to load GGUF model: "+p.string());vocab=llama_model_get_vocab(model);if(!vocab)throw Error(ExitCode::model_failure,"model vocabulary unavailable");}~Impl(){if(model)llama_model_free(model);llama_log_set(nullptr,nullptr);}};
LlamaRuntime::LlamaRuntime(std::filesystem::path p,const ModelConfig&c,std::function<void(std::string_view)>s):impl_(std::make_unique<Impl>(std::move(p),c,std::move(s))){}LlamaRuntime::~LlamaRuntime()=default;LlamaRuntime::LlamaRuntime(LlamaRuntime&&)noexcept=default;LlamaRuntime&LlamaRuntime::operator=(LlamaRuntime&&)noexcept=default;
GenerationResult LlamaRuntime::generate(std::string_view prompt,const GenerationConfig&g,std::stop_token stop){auto toks=tokenize(impl_->vocab,prompt);if(toks.empty())throw Error(ExitCode::invalid_input,"rendered prompt tokenized to empty input");if(toks.size()+g.max_tokens>impl_->cfg.context_size)throw Error(ExitCode::context_failure,"prompt plus generation exceeds configured context");auto cp=llama_context_default_params();cp.n_ctx=impl_->cfg.context_size;cp.n_batch=impl_->cfg.batch_size;cp.n_threads=threads_for(impl_->cfg.threads);cp.n_threads_batch=cp.n_threads;llama_context*ctx=llama_init_from_model(impl_->model,cp);if(!ctx)throw Error(ExitCode::context_failure,"failed to create llama context");auto ctx_guard=std::unique_ptr<llama_context,void(*)(llama_context*)>(ctx,llama_free);std::stop_token stop_copy=stop;llama_set_abort_callback(ctx,[](void*ud){return static_cast<std::stop_token*>(ud)->stop_requested();},&stop_copy);auto chain=llama_sampler_chain_init(llama_sampler_chain_default_params());if(!chain)throw Error(ExitCode::inference_failure,"failed to create sampler chain");auto smpl=std::unique_ptr<llama_sampler,void(*)(llama_sampler*)>(chain,llama_sampler_free);llama_sampler_chain_add(chain,llama_sampler_init_penalties(llama_vocab_n_tokens(impl_->vocab),g.repeat_last_n,g.repeat_penalty,0,0));llama_sampler_chain_add(chain,llama_sampler_init_top_k(g.top_k));llama_sampler_chain_add(chain,llama_sampler_init_top_p(g.top_p,1));llama_sampler_chain_add(chain,llama_sampler_init_min_p(g.min_p,1));llama_sampler_chain_add(chain,llama_sampler_init_temp(g.temperature));llama_sampler_chain_add(chain,llama_sampler_init_dist(g.seed<0?LLAMA_DEFAULT_SEED:(uint32_t)g.seed));for(auto t:toks)llama_sampler_accept(chain,t);size_t off=0;while(off<toks.size()){if(stop.stop_requested())return GenerationResult{"",(int64_t)toks.size(),0,false,true};int n=(int)(std::min)((size_t)impl_->cfg.batch_size,toks.size()-off);auto b=llama_batch_get_one(toks.data()+off,n);int rc=llama_decode(ctx,b);if(rc!=0){if(stop.stop_requested())return GenerationResult{"",(int64_t)toks.size(),0,false,true};throw Error(ExitCode::inference_failure,"llama_decode failed while evaluating prompt");}off+=(size_t)n;}GenerationResult out;out.prompt_tokens=(int64_t)toks.size();for(uint32_t i=0;i<g.max_tokens;++i){if(stop.stop_requested()){out.cancelled=true;break;}auto tok=llama_sampler_sample(chain,ctx,-1);if(llama_vocab_is_eog(impl_->vocab,tok)){out.hit_eog=true;break;}out.text+=piece(impl_->vocab,tok);++out.completion_tokens;auto b=llama_batch_get_one(&tok,1);int rc=llama_decode(ctx,b);if(rc!=0){if(stop.stop_requested()){out.cancelled=true;break;}throw Error(ExitCode::inference_failure,"llama_decode failed during generation");}}return out;}
std::string LlamaRuntime::model_description()const{std::array<char,512>b{};int n=llama_model_desc(impl_->model,b.data(),b.size());return n>0?std::string(b.data(),(std::min)(n,(int)b.size()-1)):"unknown";}std::uint64_t LlamaRuntime::model_parameter_count()const{return llama_model_n_params(impl_->model);}
}
