#include "lua_agent.hpp"
#include "error.hpp"
extern "C" {
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
}
#include <cmath>
#include <utility>
namespace g9 {
namespace {
constexpr int max_depth=128;
void set_nil(lua_State*L,const char*n){lua_pushnil(L);lua_setglobal(L,n);}void open_lib(lua_State*L,const char*n,lua_CFunction f){luaL_requiref(L,n,f,1);lua_pop(L,1);}
void push_json(lua_State*L,const JsonValue&v,int d){if(d>max_depth)throw Error(ExitCode::lua_failure,"Lua conversion depth exceeded");if(v.is_null()){lua_pushnil(L);return;}if(v.is_bool()){lua_pushboolean(L,v.as_bool());return;}if(v.is_number()){lua_pushnumber(L,v.as_number());return;}if(v.is_string()){auto&s=v.as_string();lua_pushlstring(L,s.data(),s.size());return;}if(v.is_array()){auto&a=v.as_array();lua_createtable(L,(int)a.size(),0);int i=1;for(auto&x:a){push_json(L,x,d+1);lua_seti(L,-2,i++);}return;}auto&o=v.as_object();lua_createtable(L,0,(int)o.size());for(auto&[k,x]:o){push_json(L,x,d+1);lua_setfield(L,-2,k.c_str());}}
JsonValue from_lua(lua_State*L,int idx,int d){if(d>max_depth)throw Error(ExitCode::lua_failure,"Lua conversion depth exceeded");idx=lua_absindex(L,idx);int t=lua_type(L,idx);switch(t){case LUA_TNIL:return JsonValue(nullptr);case LUA_TBOOLEAN:return JsonValue((bool)lua_toboolean(L,idx));case LUA_TNUMBER:{double n=lua_tonumber(L,idx);if(!std::isfinite(n))throw Error(ExitCode::lua_failure,"non-finite Lua number");return JsonValue(n);}case LUA_TSTRING:{size_t n;auto*s=lua_tolstring(L,idx,&n);return JsonValue(std::string(s,n));}case LUA_TTABLE:break;default:throw Error(ExitCode::lua_failure,"unsupported Lua value type");}size_t len=lua_rawlen(L,idx);bool array=true;size_t count=0;lua_pushnil(L);while(lua_next(L,idx)!=0){++count;if(!lua_isinteger(L,-2)){array=false;}else{auto k=lua_tointeger(L,-2);if(k<1||(size_t)k>len)array=false;}lua_pop(L,1);}if(array&&count==len){JsonValue::array out;out.reserve(len);for(size_t i=1;i<=len;++i){lua_geti(L,idx,(lua_Integer)i);out.push_back(from_lua(L,-1,d+1));lua_pop(L,1);}return JsonValue(std::move(out));}JsonValue::object out;lua_pushnil(L);while(lua_next(L,idx)!=0){if(lua_type(L,-2)!=LUA_TSTRING){lua_pop(L,2);throw Error(ExitCode::lua_failure,"Lua object keys must be strings");}size_t n;auto*k=lua_tolstring(L,-2,&n);out.emplace(std::string(k,n),from_lua(L,-1,d+1));lua_pop(L,1);}return JsonValue(std::move(out));}
void get_config(lua_State*L,int ref){lua_rawgeti(L,LUA_REGISTRYINDEX,ref);}void get_field(lua_State*L,int ref,const char*n){get_config(L,ref);lua_getfield(L,-1,n);lua_remove(L,-2);}std::string req_string(lua_State*L,int idx,const char*w){if(lua_type(L,idx)!=LUA_TSTRING)throw Error(ExitCode::lua_failure,std::string(w)+" must be string");size_t n;auto*s=lua_tolstring(L,idx,&n);return{s,n};}
double opt_number(lua_State*L,int table,const char*k,double d){table=lua_absindex(L,table);lua_getfield(L,table,k);double v=d;if(!lua_isnil(L,-1)){if(!lua_isnumber(L,-1))throw Error(ExitCode::lua_failure,std::string(k)+" must be number");v=lua_tonumber(L,-1);}lua_pop(L,1);return v;}bool opt_bool(lua_State*L,int table,const char*k,bool d){table=lua_absindex(L,table);lua_getfield(L,table,k);bool v=d;if(!lua_isnil(L,-1)){if(!lua_isboolean(L,-1))throw Error(ExitCode::lua_failure,std::string(k)+" must be boolean");v=lua_toboolean(L,-1)!=0;}lua_pop(L,1);return v;}std::string opt_string(lua_State*L,int table,const char*k,std::string d){table=lua_absindex(L,table);lua_getfield(L,table,k);if(!lua_isnil(L,-1))d=req_string(L,-1,k);lua_pop(L,1);return d;}void pcall(lua_State*L,int nargs,int results,const char*where){if(lua_pcall(L,nargs,results,0)!=LUA_OK){std::string e=lua_tostring(L,-1)?lua_tostring(L,-1):"Lua error";lua_pop(L,1);throw Error(ExitCode::lua_failure,std::string(where)+": "+e);}}
}
LuaAgent::LuaAgent(const std::filesystem::path&path,std::function<void(std::string_view)>sink):log_sink_(std::move(sink)){L_=luaL_newstate();if(!L_)throw Error(ExitCode::lua_failure,"cannot create Lua state");open_lib(L_,"_G",luaopen_base);open_lib(L_,LUA_TABLIBNAME,luaopen_table);open_lib(L_,LUA_STRLIBNAME,luaopen_string);open_lib(L_,LUA_MATHLIBNAME,luaopen_math);open_lib(L_,LUA_UTF8LIBNAME,luaopen_utf8);for(auto n:{"io","os","package","debug","print","dofile","loadfile","load"})set_nil(L_,n);lua_pushlightuserdata(L_,this);lua_pushcclosure(L_,[](lua_State*L)->int{auto*a=static_cast<LuaAgent*>(lua_touserdata(L,lua_upvalueindex(1)));size_t n;auto*s=luaL_checklstring(L,1,&n);if(a&&a->log_sink_)a->log_sink_(std::string_view(s,n));return 0;},1);lua_setglobal(L_,"log");if(luaL_loadfilex(L_,path.string().c_str(),nullptr)!=LUA_OK){std::string e=lua_tostring(L_,-1);throw Error(ExitCode::lua_failure,"load config: "+e);}pcall(L_,0,1,"execute config");if(!lua_istable(L_,-1))throw Error(ExitCode::lua_failure,"config must return a table");config_ref_=luaL_ref(L_,LUA_REGISTRYINDEX);load_typed_config();}
LuaAgent::~LuaAgent(){if(L_)lua_close(L_);}LuaAgent::LuaAgent(LuaAgent&&o)noexcept:L_(std::exchange(o.L_,nullptr)),config_ref_(std::exchange(o.config_ref_,-1)),log_sink_(std::move(o.log_sink_)),model_(std::move(o.model_)),generation_(o.generation_),loop_(o.loop_){}LuaAgent&LuaAgent::operator=(LuaAgent&&o)noexcept{if(this!=&o){if(L_)lua_close(L_);L_=std::exchange(o.L_,nullptr);config_ref_=std::exchange(o.config_ref_,-1);log_sink_=std::move(o.log_sink_);model_=std::move(o.model_);generation_=o.generation_;loop_=o.loop_;}return *this;}
void LuaAgent::load_typed_config(){get_field(L_,config_ref_,"model");if(lua_istable(L_,-1)){model_.path=opt_string(L_,-1,"path",model_.path.string());model_.context_size=(uint32_t)opt_number(L_,-1,"context_size",model_.context_size);model_.batch_size=(uint32_t)opt_number(L_,-1,"batch_size",model_.batch_size);model_.gpu_layers=(int)opt_number(L_,-1,"gpu_layers",0);model_.threads=(int)opt_number(L_,-1,"threads",0);}lua_pop(L_,1);if(model_.context_size<256||model_.context_size>131072||model_.batch_size<1||model_.batch_size>model_.context_size)throw Error(ExitCode::lua_failure,"invalid model config");get_field(L_,config_ref_,"generation");if(lua_istable(L_,-1)){generation_.thinking=opt_bool(L_,-1,"thinking",false);generation_.max_tokens=(uint32_t)opt_number(L_,-1,"max_tokens",768);generation_.temperature=(float)opt_number(L_,-1,"temperature",.7);generation_.top_p=(float)opt_number(L_,-1,"top_p",.95);generation_.top_k=(int)opt_number(L_,-1,"top_k",40);generation_.min_p=(float)opt_number(L_,-1,"min_p",0);generation_.repeat_penalty=(float)opt_number(L_,-1,"repeat_penalty",1);generation_.repeat_last_n=(int)opt_number(L_,-1,"repeat_last_n",64);generation_.seed=(int64_t)opt_number(L_,-1,"seed",-1);}lua_pop(L_,1);get_field(L_,config_ref_,"loop");if(lua_istable(L_,-1)){loop_.max_steps=(uint32_t)opt_number(L_,-1,"max_steps",32);loop_.max_tool_calls_per_step=(uint32_t)opt_number(L_,-1,"max_tool_calls_per_step",8);loop_.max_tool_result_bytes=(size_t)opt_number(L_,-1,"max_tool_result_bytes",65536);}lua_pop(L_,1);if(generation_.max_tokens<1||generation_.max_tokens>16384||generation_.top_p<0||generation_.top_p>1||generation_.min_p<0||generation_.min_p>1||generation_.temperature<0||generation_.temperature>5||loop_.max_steps<1||loop_.max_steps>256)throw Error(ExitCode::lua_failure,"invalid generation/loop config");}
AgentRequest LuaAgent::before_prompt(const AgentRequest&r){get_field(L_,config_ref_,"before_prompt");if(lua_isnil(L_,-1)){lua_pop(L_,1);return r;}if(!lua_isfunction(L_,-1)){lua_pop(L_,1);throw Error(ExitCode::lua_failure,"before_prompt must be function");}push_json(L_,JsonValue(JsonValue::object{{"prompt",r.prompt},{"context",r.context},{"options",r.options}}),0);pcall(L_,1,1,"before_prompt");auto v=from_lua(L_,-1,0);lua_pop(L_,1);if(!v.is_object())throw Error(ExitCode::lua_failure,"before_prompt must return object");AgentRequest out=r;if(auto*x=object_get(v.as_object(),"prompt");x&&x->is_string())out.prompt=x->as_string();if(auto*x=object_get(v.as_object(),"context"))out.context=*x;if(auto*x=object_get(v.as_object(),"options"))out.options=*x;return out;}
std::vector<ChatMessage>LuaAgent::build_messages(const AgentRequest&r){get_field(L_,config_ref_,"build_messages");if(lua_isnil(L_,-1)){lua_pop(L_,1);return{{"user",r.prompt}};}push_json(L_,JsonValue(JsonValue::object{{"prompt",r.prompt},{"context",r.context},{"options",r.options}}),0);pcall(L_,1,1,"build_messages");auto v=from_lua(L_,-1,0);lua_pop(L_,1);if(!v.is_array())throw Error(ExitCode::lua_failure,"build_messages must return array");std::vector<ChatMessage>out;for(auto&m:v.as_array()){if(!m.is_object())throw Error(ExitCode::lua_failure,"message must be object");auto*role=object_get(m.as_object(),"role");auto*content=object_get(m.as_object(),"content");if(!role||!content||!role->is_string()||!content->is_string())throw Error(ExitCode::lua_failure,"message requires role/content");out.push_back({role->as_string(),content->as_string()});}return out;}
std::string LuaAgent::render_prompt(const std::vector<ChatMessage>&msgs,const GenerationConfig&g,const JsonValue&tools,const JsonValue&history){get_field(L_,config_ref_,"render_prompt");if(!lua_isfunction(L_,-1)){lua_pop(L_,1);throw Error(ExitCode::lua_failure,"render_prompt function required");}JsonValue::array ma;for(auto&m:msgs)ma.emplace_back(JsonValue::object{{"role",m.role},{"content",m.content}});push_json(L_,JsonValue(std::move(ma)),0);push_json(L_,JsonValue(JsonValue::object{{"thinking",g.thinking}}),0);push_json(L_,tools,0);push_json(L_,history,0);pcall(L_,4,1,"render_prompt");auto out=req_string(L_,-1,"render_prompt result");lua_pop(L_,1);return out;}
GenerationConfig LuaAgent::generation_settings(const AgentRequest&r){auto g=generation_;get_field(L_,config_ref_,"generation_settings");if(lua_isnil(L_,-1)){lua_pop(L_,1);return g;}push_json(L_,JsonValue(JsonValue::object{{"prompt",r.prompt},{"options",r.options}}),0);pcall(L_,1,1,"generation_settings");if(lua_istable(L_,-1)){g.thinking=opt_bool(L_,-1,"thinking",g.thinking);g.max_tokens=(uint32_t)opt_number(L_,-1,"max_tokens",g.max_tokens);g.temperature=(float)opt_number(L_,-1,"temperature",g.temperature);g.top_p=(float)opt_number(L_,-1,"top_p",g.top_p);g.top_k=(int)opt_number(L_,-1,"top_k",g.top_k);}lua_pop(L_,1);return g;}
AgentResponse LuaAgent::after_response(const AgentResponse&r){get_field(L_,config_ref_,"after_response");if(lua_isnil(L_,-1)){lua_pop(L_,1);return r;}push_json(L_,JsonValue(JsonValue::object{{"output",r.output},{"model",r.model},{"metadata",r.metadata}}),0);pcall(L_,1,1,"after_response");auto v=from_lua(L_,-1,0);lua_pop(L_,1);auto out=r;if(v.is_object()){if(auto*x=object_get(v.as_object(),"output");x&&x->is_string())out.output=x->as_string();if(auto*x=object_get(v.as_object(),"metadata"))out.metadata=*x;}return out;}
}
