#include "patch_engine.hpp"
#include "error.hpp"
#include <fstream>
#include <set>
#include <unistd.h>
namespace g9 { namespace { [[noreturn]]void pf(const std::string&m){throw Error(ExitCode::invalid_input,"patch: "+m);}std::vector<std::string>ls(std::string_view s){std::vector<std::string>o;size_t p=0;while(p<s.size()){auto n=s.find('\n',p);if(n==std::string_view::npos){o.emplace_back(s.substr(p));break;}o.emplace_back(s.substr(p,n-p+1));p=n+1;}return o;}std::string read(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)pf("read "+p.string());return{std::istreambuf_iterator<char>(f),{}};}std::string hunks(std::string x,const std::vector<PatchHunk>&hs){for(auto&h:hs){auto p=x.find(h.before);if(p==std::string::npos)pf("context not found");if(x.find(h.before,p+1)!=std::string::npos)pf("ambiguous context");x.replace(p,h.before.size(),h.after);}return x;}size_t lc(std::string_view s){size_t n=0;for(char c:s)if(c=='\n')++n;return n+(!s.empty()&&s.back()!='\n');}}
PatchPlan parse_patch(std::string_view text){auto l=ls(text);if(l.empty()||l[0]!="*** Begin Patch\n")pf("missing Begin Patch");auto strip=[](std::string s){if(!s.empty()&&s.back()=='\n')s.pop_back();return s;};PatchPlan p;std::set<std::string>seen;size_t i=1;while(i<l.size()){auto m=strip(l[i]);if(m=="*** End Patch"){++i;for(;i<l.size();++i)if(!strip(l[i]).empty())pf("text after End Patch");return p;}PatchOperation o;std::string pre;if(m.rfind("*** Add File: ",0)==0){o.kind=PatchKind::add;pre="*** Add File: ";}else if(m.rfind("*** Update File: ",0)==0){o.kind=PatchKind::update;pre="*** Update File: ";}else if(m.rfind("*** Delete File: ",0)==0){o.kind=PatchKind::remove;pre="*** Delete File: ";}else pf("file marker");o.path=m.substr(pre.size());if(o.path.empty()||o.path.is_absolute()||!seen.insert(o.path.generic_string()).second)pf("invalid/duplicate path");++i;if(o.kind==PatchKind::add){while(i<l.size()&&l[i].rfind("*** ",0)!=0){if(l[i].empty()||l[i][0]!='+')pf("add line");o.content+=l[i].substr(1);++i;}}else if(o.kind==PatchKind::update){while(i<l.size()&&l[i].rfind("*** ",0)!=0){if(strip(l[i])!="@@")pf("hunk marker");++i;PatchHunk h;while(i<l.size()&&l[i].rfind("*** ",0)!=0&&strip(l[i])!="@@"){char c=l[i][0];auto b=l[i].substr(1);if(c==' '){h.before+=b;h.after+=b;}else if(c=='-')h.before+=b;else if(c=='+')h.after+=b;else pf("hunk line");++i;}if(h.before.empty()&&h.after.empty())pf("empty hunk");o.hunks.push_back(std::move(h));}if(o.hunks.empty())pf("no hunks");}p.operations.push_back(std::move(o));}pf("missing End Patch");}
PatchPlan validate_patch(const Workspace&w,const PatchPlan&p){for(auto&o:p.operations){auto d=w.resolve(o.path,o.kind==PatchKind::remove?Operation::remove:Operation::write,o.kind==PatchKind::add);if(!d.allowed)pf(d.reason);bool e=std::filesystem::exists(d.canonical_path);if(o.kind==PatchKind::add&&e)pf("add exists");if(o.kind!=PatchKind::add&&!e)pf("target missing");if(o.kind==PatchKind::update)(void)hunks(read(d.canonical_path),o.hunks);}return p;}
PatchResult apply_patch(const Workspace&w,const PatchPlan&p){struct I{std::filesystem::path path;bool existed;std::string oldv,newv;PatchKind kind;};std::vector<I>is;for(auto&o:p.operations){auto d=w.resolve(o.path,o.kind==PatchKind::remove?Operation::remove:Operation::write,o.kind==PatchKind::add);I x{d.canonical_path,std::filesystem::exists(d.canonical_path),{}, {},o.kind};if(x.existed)x.oldv=read(x.path);x.newv=o.kind==PatchKind::add?o.content:o.kind==PatchKind::update?hunks(x.oldv,o.hunks):"";is.push_back(std::move(x));}PatchResult r;size_t done=0;try{for(auto&x:is){if(x.kind==PatchKind::remove)std::filesystem::remove(x.path);else{std::filesystem::create_directories(x.path.parent_path());auto tmp=x.path;tmp += ".g9tmp."+std::to_string(::getpid());{std::ofstream f(tmp,std::ios::binary|std::ios::trunc);f.write(x.newv.data(),(std::streamsize)x.newv.size());if(!f)pf("write temp");}std::filesystem::rename(tmp,x.path);}++done;r.files.push_back({std::filesystem::relative(x.path,w.root()),lc(x.newv),lc(x.oldv),x.kind});}}catch(...){r.rollback_attempted=true;for(size_t n=done;n>0;--n){auto&x=is[n-1];try{if(!x.existed)std::filesystem::remove(x.path);else{std::ofstream f(x.path,std::ios::binary|std::ios::trunc);f.write(x.oldv.data(),(std::streamsize)x.oldv.size());}}catch(...){r.rollback_complete=false;}}throw;}return r;}
} // namespace g9
