#include "process.hpp"
#include "error.hpp"
#include <cerrno>
#include <csignal>
#include <fcntl.h>
#include <poll.h>
#include <sys/wait.h>
#include <unistd.h>
namespace g9 { namespace { std::string base(std::string s){auto p=s.find_last_of('/');return p==std::string::npos?s:s.substr(p+1);}bool has_url(const std::vector<std::string>&a){for(auto&s:a)if(s.find("http://")!=std::string::npos||s.find("https://")!=std::string::npos)return true;return false;}std::filesystem::path exe(const std::string&e,const std::map<std::string,std::string>&env){if(e.find('/')!=std::string::npos)return e;std::string path=env.contains("PATH")?env.at("PATH"):(getenv("PATH")?getenv("PATH"):"/usr/bin:/bin");size_t p=0;while(p<=path.size()){auto n=path.find(':',p);auto c=std::filesystem::path(path.substr(p,n==std::string::npos?std::string::npos:n-p))/e;if(access(c.c_str(),X_OK)==0)return c;if(n==std::string::npos)break;p=n+1;}throw Error(ExitCode::process_failure,"executable not found: "+e);}void app(std::string&d,const char*b,size_t n,size_t cap,bool&t){if(d.size()+n<=cap){d.append(b,n);return;}t=true;if(!cap)return;size_t h=cap/2;if(d.size()>h)d.resize(h);size_t tail=cap-d.size();if(n>=tail)d.append(b+n-tail,tail);else{if(d.size()>tail-n)d.resize(tail-n);d.append(b,n);}} }
CommandClass CommandPolicy::classify(const std::vector<std::string>&a)const{if(a.empty())return CommandClass::denied;auto e=base(a[0]);if(has_url(a)||e=="curl"||e=="wget"||e=="ssh"||e=="scp"||e=="nc"||e=="ncat")return CommandClass::denied;if(e=="git"){if(a.size()<2)return CommandClass::ask;auto s=a[1];if(s=="push"||s=="pull"||s=="fetch"||s=="remote")return CommandClass::denied;if(s=="reset"||s=="clean")return CommandClass::destructive;if(s=="status"||s=="diff"||s=="show"||s=="log"||s=="grep"||s=="rev-parse")return CommandClass::known_safe;return CommandClass::ask;}if(e=="make"||e=="ninja"){for(auto&s:a)if(s=="clean"||s=="distclean")return CommandClass::destructive;return CommandClass::known_safe;}if(e=="cmake"){for(size_t i=0;i+1<a.size();++i)if((a[i]=="--target"||a[i]=="-t")&&(a[i+1]=="clean"||a[i+1]=="install"))return CommandClass::destructive;return CommandClass::known_safe;}if(e=="ctest"||e=="clang"||e=="clang++"||e=="gcc"||e=="g++")return CommandClass::known_safe;return CommandClass::ask;}
RiskClass CommandPolicy::risk(const std::vector<std::string>&a)const{auto c=classify(a);if(c==CommandClass::denied)return RiskClass::forbidden;if(c==CommandClass::destructive)return!a.empty()&&base(a[0])=="git"?RiskClass::vcs_destructive:RiskClass::filesystem_destructive;if(!a.empty()&&base(a[0])=="git")return a.size()>1&&(a[1]=="status"||a[1]=="diff"||a[1]=="show"||a[1]=="log"||a[1]=="grep"||a[1]=="rev-parse")?RiskClass::vcs_read:RiskClass::vcs_write;return RiskClass::execute;}
std::map<std::string,std::string> minimal_environment(std::filesystem::path h,std::filesystem::path t){std::map<std::string,std::string>e{{"HOME",h.string()},{"TMPDIR",t.string()},{"PATH","/usr/local/bin:/usr/bin:/bin"},{"LANG","C.UTF-8"}};for(auto k:{"CC","CXX","CMAKE_PREFIX_PATH","SDKROOT"})if(auto*v=getenv(k))e[k]=v;return e;}
ProcessResult run_process(const ProcessSpec&s,ChildSetup setup,std::stop_token stop){if(s.argv.empty())throw Error(ExitCode::process_failure,"empty argv");int o[2],e[2];if(pipe(o)||pipe(e))throw Error(ExitCode::process_failure,"pipe failed");auto x=exe(s.argv[0],s.environment);auto begin=std::chrono::steady_clock::now();pid_t pid=fork();if(pid<0)throw Error(ExitCode::process_failure,"fork failed");if(pid==0){setpgid(0,0);dup2(o[1],1);dup2(e[1],2);close(o[0]);close(o[1]);close(e[0]);close(e[1]);if(chdir(s.cwd.c_str())!=0)_exit(126);clearenv();for(auto&[k,v]:s.environment)setenv(k.c_str(),v.c_str(),1);if(setup)try{setup();}catch(...){_exit(125);}std::vector<char*>av;for(auto&q:s.argv)av.push_back(const_cast<char*>(q.c_str()));av.push_back(nullptr);execv(x.c_str(),av.data());_exit(127);}close(o[1]);close(e[1]);fcntl(o[0],F_SETFL,O_NONBLOCK);fcntl(e[0],F_SETFL,O_NONBLOCK);ProcessResult r;bool oo=true,eo=true,done=false,term=false;int st=0;auto deadline=begin+s.timeout,term_at=begin;while(oo||eo||!done){pollfd f[2]{{o[0],POLLIN,0},{e[0],POLLIN,0}};poll(f,2,20);char b[4096];auto drain=[&](int fd,bool&open,std::string&dst,bool&tr){for(;;){ssize_t n=read(fd,b,sizeof b);if(n>0)app(dst,b,(size_t)n,s.max_output_bytes,tr);else if(n==0){open=false;close(fd);break;}else if(errno==EAGAIN||errno==EWOULDBLOCK)break;else{open=false;close(fd);break;}}};if(oo)drain(o[0],oo,r.stdout_text,r.stdout_truncated);if(eo)drain(e[0],eo,r.stderr_text,r.stderr_truncated);if(!done&&waitpid(pid,&st,WNOHANG)==pid)done=true;auto now=std::chrono::steady_clock::now();if(!done&&!term&&(stop.stop_requested()||now>=deadline)){r.cancelled=stop.stop_requested();r.timed_out=!r.cancelled;kill(-pid,SIGTERM);term=true;term_at=now;}if(!done&&term&&now-term_at>std::chrono::milliseconds(500))kill(-pid,SIGKILL);}r.exit_code=WIFEXITED(st)?WEXITSTATUS(st):WIFSIGNALED(st)?128+WTERMSIG(st):-1;r.duration=std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-begin);return r;}
} // namespace g9
