#include "tool_protocol.hpp"
#include "error.hpp"
#include <charconv>
#include <cctype>
#include <cmath>
#include <cstdlib>
#include <set>
namespace g9 {
namespace {
std::string decode_entities(std::string_view in){std::string out;out.reserve(in.size());for(size_t i=0;i<in.size();){if(in[i]!='&'){out.push_back(in[i++]);continue;}auto semi=in.find(';',i+1);if(semi==std::string_view::npos)throw Error(ExitCode::tool_protocol_failure,"unterminated XML entity");auto e=in.substr(i,semi-i+1);if(e=="&amp;")out+='&';else if(e=="&lt;")out+='<';else if(e=="&gt;")out+='>';else if(e=="&quot;")out+='"';else if(e=="&apos;")out+='\'';else throw Error(ExitCode::tool_protocol_failure,"unsupported XML entity");i=semi+1;}return out;}
bool starts(std::string_view s,size_t p,std::string_view x){return p<=s.size()&&s.substr(p,x.size())==x;}
std::string parse_quoted_attr(std::string_view text,size_t& p,std::string_view prefix){if(!starts(text,p,prefix))throw Error(ExitCode::tool_protocol_failure,"malformed tool attribute");p+=prefix.size();auto q=text.find('"',p);if(q==std::string_view::npos)throw Error(ExitCode::tool_protocol_failure,"unterminated tool attribute");if(q-p>128)throw Error(ExitCode::tool_protocol_failure,"tool attribute too long");auto v=std::string(text.substr(p,q-p));p=q+1;return v;}
JsonValue coerce(std::string_view raw,const JsonValue* schema){std::string type="string";if(schema&&schema->is_object())if(auto*t=object_get(schema->as_object(),"type");t&&t->is_string())type=t->as_string();auto trimmed=[&](){size_t a=0,b=raw.size();while(a<b&&std::isspace((unsigned char)raw[a]))++a;while(b>a&&std::isspace((unsigned char)raw[b-1]))--b;return raw.substr(a,b-a);}();if(type=="string")return JsonValue(decode_entities(raw));if(type=="boolean"){if(trimmed=="true")return JsonValue(true);if(trimmed=="false")return JsonValue(false);throw Error(ExitCode::tool_protocol_failure,"invalid boolean parameter");}if(type=="integer"){long long v{};auto[ptr,ec]=std::from_chars(trimmed.data(),trimmed.data()+trimmed.size(),v);if(ec!=std::errc{}||ptr!=trimmed.data()+trimmed.size())throw Error(ExitCode::tool_protocol_failure,"invalid integer parameter");return JsonValue((double)v);}if(type=="number"){std::string tmp(trimmed);char*end=nullptr;errno=0;double v=std::strtod(tmp.c_str(),&end);if(errno||!end||*end||!std::isfinite(v))throw Error(ExitCode::tool_protocol_failure,"invalid number parameter");return JsonValue(v);}if(type=="object"||type=="array")return parse_json(trimmed);return JsonValue(decode_entities(raw));}
const JsonValue* property_schema(const ToolDefinition& def,std::string_view name){if(!def.input_schema.is_object())return nullptr;auto*props=object_get(def.input_schema.as_object(),"properties");if(!props||!props->is_object())return nullptr;return object_get(props->as_object(),name);}
void validate_required(const ToolDefinition& def,const JsonValue::object& args){if(!def.input_schema.is_object())return;auto*req=object_get(def.input_schema.as_object(),"required");if(req&&req->is_array())for(auto&r:req->as_array())if(r.is_string()&&!args.contains(r.as_string()))throw Error(ExitCode::tool_protocol_failure,"missing required tool parameter: "+r.as_string());auto*add=object_get(def.input_schema.as_object(),"additionalProperties");bool no_extra=add&&add->is_bool()&&!add->as_bool();if(no_extra){auto*props=object_get(def.input_schema.as_object(),"properties");for(auto&[k,v]:args)if(!props||!props->is_object()||!props->as_object().contains(k))throw Error(ExitCode::tool_protocol_failure,"unexpected tool parameter: "+k);}}
std::string tool_hint(std::string_view n){
if(n=="apply_patch")return R"(apply_patch needs "patch" in this format:
<function name="apply_patch"><param name="patch">*** Begin Patch
*** Update File: FILE
@@
-old
+new
*** End Patch</param></function>
Read the file first; the - and + lines must match its exact content.)";
if(n=="replace_text")return R"(replace_text needs path, old_text, new_text and expected_occurrences (an integer equal to how many times old_text appears). Example: <function name="replace_text"><param name="path">a.txt</param><param name="old_text">red</param><param name="new_text">blue</param><param name="expected_occurrences">1</param></function>)";
if(n=="write_file")return R"(write_file needs path and content. To overwrite an existing file add <param name="overwrite">true</param> (boolean: exactly true or false).)";
if(n=="run_command")return R"(run_command needs "command" as a JSON array of strings. Example: <function name="run_command"><param name="command">["ls","-la"]</param></function>)";
if(n=="delete_file")return R"(delete_file needs path. Example: <function name="delete_file"><param name="path">notes.txt</param></function>)";
if(n=="find_files")return R"(find_files needs pattern; use ** to cross directories. Example: <function name="find_files"><param name="pattern">**/*.cpp</param></function>)";
if(n=="search_text")return R"(search_text needs query. Example: <function name="search_text"><param name="query">main</param></function>)";
if(n=="read_file")return R"(read_file needs path. Example: <function name="read_file"><param name="path">README.md</param></function>)";
if(n=="list_files")return R"(list_files example: <function name="list_files"><param name="depth">2</param></function>)";
return "";
}
}
JsonValue tool_definitions_to_prompt_json(const std::vector<ToolDefinition>& tools){JsonValue::array a;for(auto&t:tools)a.emplace_back(JsonValue::object{{"name",t.name},{"description",t.description},{"parameters",t.input_schema}});return a;}
ParsedAssistantTurn parse_g9_assistant_turn(std::string_view text,const ToolRegistry& registry){ParsedAssistantTurn out;size_t p=0,visible=0;try{while(true){auto f=text.find("<function ",p);if(f==std::string_view::npos){out.visible_text+=std::string(text.substr(visible));break;}out.visible_text+=std::string(text.substr(visible,f-visible));size_t q=f+10;auto name=parse_quoted_attr(text,q,"name=\"");if(q>=text.size()||text[q]!='>')throw Error(ExitCode::tool_protocol_failure,"malformed function start tag");++q;const ToolDefinition*def=registry.definition(name);if(!def)throw Error(ExitCode::tool_protocol_failure,"unknown tool: "+name);JsonValue::object args;std::set<std::string>seen;while(!starts(text,q,"</function>")){if(!starts(text,q,"<param "))throw Error(ExitCode::tool_protocol_failure,"malformed function body");q+=7;auto pn=parse_quoted_attr(text,q,"name=\"");if(q>=text.size()||text[q]!='>')throw Error(ExitCode::tool_protocol_failure,"malformed param start tag");++q;if(!seen.insert(pn).second)throw Error(ExitCode::tool_protocol_failure,"duplicate tool parameter: "+pn);std::string raw;if(starts(text,q,"<![CDATA[")){q+=9;auto end=text.find("]]>",q);if(end==std::string_view::npos)throw Error(ExitCode::tool_protocol_failure,"unterminated CDATA");raw=std::string(text.substr(q,end-q));q=end+3;}else{auto end=text.find("</param>",q);if(end==std::string_view::npos)throw Error(ExitCode::tool_protocol_failure,"unterminated param");raw=std::string(text.substr(q,end-q));q=end;}if(!starts(text,q,"</param>"))throw Error(ExitCode::tool_protocol_failure,"missing param close tag");q+=8;args.emplace(pn,coerce(raw,property_schema(*def,pn)));}q+=11;validate_required(*def,args);out.tool_calls.push_back({name,JsonValue(std::move(args)),std::string(text.substr(f,q-f))});p=q;visible=q;}}catch(const std::exception&e){out.malformed_tool_markup=true;out.parse_error=e.what();out.visible_text=std::string(text);out.tool_calls.clear();}return out;}
std::string tool_format_hint(){return R"(Emit exactly one tool call as: <function name="TOOL"><param name="arg">value</param></function>. Booleans are exactly "true" or "false"; integers are plain numbers; run_command "command" is a JSON array of strings.)";}
std::string make_g9_error_response(std::string_view error){JsonValue::object body{{"ok",false},{"error",std::string(error)},{"hint",tool_format_hint()}};return "<tool_response>"+serialize_json(JsonValue(std::move(body)))+"</tool_response>";}
std::string make_g9_tool_response(std::string_view tool_name,const ToolResult& result){JsonValue::object body{{"tool",std::string(tool_name)},{"ok",result.ok},{"disposition",to_string(result.disposition)},{"result",result.payload}};if(!result.ok&&result.disposition==ToolDisposition::failed){auto h=tool_hint(tool_name);if(h.empty())h=tool_format_hint();body["hint"]=std::move(h);}return "<tool_response>"+serialize_json(JsonValue(std::move(body)))+"</tool_response>";}
}
