#include "workspace.hpp"
#include <algorithm>
#include <stdexcept>
#include <system_error>
namespace g9 {
namespace {
std::string slash(std::filesystem::path p){return p.generic_string();}
bool beneath(const std::filesystem::path&r,const std::filesystem::path&p){auto rn=r.lexically_normal();auto pn=p.lexically_normal();auto ri=rn.begin(),re=rn.end(),pi=pn.begin();for(;ri!=re;++ri,++pi)if(pi==pn.end()||*ri!=*pi)return false;return true;}
bool contains(const std::filesystem::path&s,const std::filesystem::path&r){auto sn=s.lexically_normal();if(sn=="."||sn.empty())return true;auto si=sn.begin(),ri=r.begin();for(;si!=sn.end();++si,++ri)if(ri==r.end()||*si!=*ri)return false;return true;}
bool gm(std::string_view p,size_t pi,std::string_view t,size_t ti){while(pi<p.size()){if(p[pi]=='*'){bool d=pi+1<p.size()&&p[pi+1]=='*';pi+=d?2:1;if(pi==p.size())return d||t.find('/',ti)==std::string_view::npos;for(size_t k=ti;k<=t.size();++k){if(!d&&k>ti&&t[k-1]=='/')break;if(gm(p,pi,t,k))return true;}return false;}if(ti>=t.size())return false;if(p[pi]=='?'){if(t[ti]=='/')return false;++pi;++ti;continue;}if(p[pi]!=t[ti])return false;++pi;++ti;}return ti==t.size();}
}
bool glob_match(std::string_view p,std::string_view t){return gm(p,0,t,0);}
Workspace::Workspace(std::filesystem::path root,Access d,std::vector<ScopeRule>s,std::vector<std::string>g,bool f):default_access_(d),scopes_(std::move(s)),deny_globs_(std::move(g)),follow_directory_symlinks_(f){std::error_code ec;root_=std::filesystem::weakly_canonical(root,ec);if(ec||root_.empty()||!std::filesystem::is_directory(root_))throw std::runtime_error("workspace root must be an existing directory");for(auto&x:scopes_){if(x.relative_path.is_absolute())throw std::runtime_error("workspace scope must be relative");x.relative_path=x.relative_path.lexically_normal();}}
bool Workspace::is_denied(std::filesystem::path r)const{auto x=slash(r.lexically_normal());return std::any_of(deny_globs_.begin(),deny_globs_.end(),[&](auto&p){return glob_match(p,x);});}
PathDecision Workspace::resolve(std::filesystem::path r,Operation op,bool may)const{PathDecision out;if(r.empty())r=".";if(r.is_absolute()){out.reason="absolute paths are outside workspace";return out;}r=r.lexically_normal();if(r==".."||(!r.empty()&&*r.begin()=="..")){out.reason="path escapes workspace";return out;}auto lexical=(root_/r).lexically_normal();if(!beneath(root_,lexical)){out.reason="path escapes workspace";return out;}std::filesystem::path existing=lexical;std::vector<std::filesystem::path> tail;std::error_code ec;while(!std::filesystem::exists(existing,ec)){if(!may||existing==root_){out.reason="path does not exist";return out;}tail.push_back(existing.filename());existing=existing.parent_path();ec.clear();}auto prefix=std::filesystem::weakly_canonical(existing,ec);if(ec||!beneath(root_,prefix)){out.reason="symlink/canonical path escapes workspace";return out;}auto resolved=prefix;for(auto it=tail.rbegin();it!=tail.rend();++it)resolved/=*it;resolved=resolved.lexically_normal();if(!beneath(root_,resolved)){out.reason="resolved path escapes workspace";return out;}auto rr=std::filesystem::relative(resolved,root_,ec);if(ec){out.reason="cannot make relative path";return out;}if(is_denied(rr)){out.reason="path matches deny rule";out.canonical_path=resolved;return out;}Access access=default_access_;size_t best=0;for(auto&rule:scopes_)if(contains(rule.relative_path,rr)){auto depth=(size_t)std::distance(rule.relative_path.begin(),rule.relative_path.end());if(depth>=best){best=depth;access=rule.access;}}bool write=op==Operation::write||op==Operation::remove;out.allowed=write?access==Access::read_write:access!=Access::none;out.canonical_path=resolved;out.effective_access=access;out.reason=out.allowed?"allowed":write?"write access denied by scope":"read access denied by scope";return out;}
} // namespace g9
